# 03 Keyword Analysis

This notebook analyzes the keyword-search results and answers the project's
expected outcomes.

## Expected Outcomes

- Identify customers’ concerns about loan and insurance products.
- Determine why customers contacted the chatbot.
- Identify questions and interest related to marketing campaigns.
- Extract common product conditions, requirements, and customer needs.
- Provide insights that can help the marketing team improve campaigns and
  better address customer demand.

The analysis is performed at both the message level and the `userID` level.
Message-level analysis measures how frequently topics appear, while
`userID`-level analysis reduces repeated counting when the same customer sends
multiple messages.

Import Libraries

In [21]:
import pandas as pd
from pathlib import Path

Load the keyword results

In [22]:
project_root = Path.cwd().parent.parent

keyword_results_path = (
    project_root
    / "data"
    / "processed"
    / "keyword_search_results.csv"
)

print("File exists:", keyword_results_path.exists())

File exists: True

Load the file:

In [23]:
keyword_df = pd.read_csv(keyword_results_path)

print("Keyword results loaded successfully.")

Keyword results loaded successfully.

Restore Boolean columns

In [24]:
category_columns = ['loan_product',
 'insurance_product',
 'car_loan',
 'motorcycle_loan',
 'land_loan',
 'refinancing',
 'car_insurance',
 'motorcycle_insurance',
 'other_insurance_product',
 'eligibility',
 'application_process',
 'required_documents',
 'approval_and_status',
 'interest_and_fees',
 'credit_limit',
 'payment_and_installment',
 'insurance_premium',
 'insurance_claim',
 'coverage_and_conditions',
 'renewal_and_cancellation',
 'interest_rate',
 'fees',
 'loan_installment_repayment',
 'insurance_premium_payment',
 'payment_channel',
 'payment_status',
 'overdue_payment',
 'insurance_coverage',
 'renewal',
 'cancellation',
 'approval_application_status',
 'requesting_information',
 'applying',
 'checking_eligibility',
 'checking_status',
 'making_payment',
 'making_claim',
 'renewing',
 'cancelling',
 'contacting_staff',
 'finding_branch',
 'campaign_or_promotion',
 'campaign_interest',
 'campaign_eligibility',
 'campaign_registration',
 'campaign_benefits',
 'campaign_period_deadline',
 'branch_or_contact']

missing_category_columns = [
    column for column in category_columns
    if column not in keyword_df.columns
]

if missing_category_columns:
    print("Missing category columns. Run notebook 02 before this notebook:")
    print(missing_category_columns)

In [25]:
for column in category_columns:
    if column not in keyword_df.columns:
        continue

    if keyword_df[column].dtype == "object":
        keyword_df[column] = (
            keyword_df[column]
            .astype(str)
            .str.lower()
            .map({"true": True, "false": False})
            .fillna(False)
            .astype(bool)
        )

Create conversation-level results

In [26]:
conversation_results = (
    keyword_df.groupby("userID")[category_columns]
    .max()
    .reset_index()
)

print("Conversation-level results created successfully.")

Conversation-level results created successfully.

readable category names

In [27]:
category_labels = {'loan_product': 'Loan product',
 'insurance_product': 'Insurance product',
 'eligibility': 'Eligibility',
 'application_process': 'Application process',
 'required_documents': 'Required documents',
 'approval_and_status': 'Approval and status',
 'interest_and_fees': 'Interest and fees',
 'credit_limit': 'Credit limit',
 'payment_and_installment': 'Payment and installment',
 'insurance_premium': 'Insurance premium',
 'insurance_claim': 'Insurance claim',
 'coverage_and_conditions': 'Coverage and conditions',
 'renewal_and_cancellation': 'Renewal and cancellation',
 'campaign_or_promotion': 'Campaign or promotion',
 'campaign_interest': 'Campaign interest',
 'branch_or_contact': 'Branch or contact',
 'car_loan': 'Car loan',
 'motorcycle_loan': 'Motorcycle loan',
 'land_loan': 'Land loan',
 'refinancing': 'Refinancing',
 'car_insurance': 'Car insurance',
 'motorcycle_insurance': 'Motorcycle insurance',
 'other_insurance_product': 'Other insurance product',
 'interest_rate': 'Interest rate',
 'fees': 'Fees',
 'loan_installment_repayment': 'Loan installment or repayment',
 'insurance_premium_payment': 'Insurance premium payment',
 'payment_channel': 'Payment channel',
 'payment_status': 'Payment status',
 'overdue_payment': 'Overdue payment',
 'insurance_coverage': 'Insurance coverage',
 'renewal': 'Renewal',
 'cancellation': 'Cancellation',
 'approval_application_status': 'Approval or application status',
 'requesting_information': 'Requesting information',
 'applying': 'Applying',
 'checking_eligibility': 'Checking eligibility',
 'checking_status': 'Checking status',
 'making_payment': 'Making a payment',
 'making_claim': 'Making a claim',
 'renewing': 'Renewing',
 'cancelling': 'Cancelling',
 'contacting_staff': 'Contacting staff',
 'finding_branch': 'Finding a branch',
 'campaign_eligibility': 'Campaign eligibility',
 'campaign_registration': 'Campaign registration',
 'campaign_benefits': 'Campaign benefits',
 'campaign_period_deadline': 'Campaign period or deadline'}

Outcome 1: Customer Concerns About Loan and Insurance Products

This section identifies the most common concern categories appearing in
conversations associated with loan and insurance products.

In [28]:
concern_columns = [
    "eligibility",
    "application_process",
    "required_documents",
    "approval_and_status",
    "interest_and_fees",
    "credit_limit",
    "payment_and_installment",
    "insurance_premium",
    "insurance_claim",
    "coverage_and_conditions",
    "renewal_and_cancellation"
]

Loan Concerns

In [29]:
loan_concerns = (
    conversation_results.loc[
        conversation_results["loan_product"],
        concern_columns
    ]
    .sum()
    .sort_values(ascending=False)
    .rename("conversation_count")
    .reset_index()
    .rename(columns={"index": "concern"})
)

loan_concerns["concern"] = loan_concerns["concern"].map(
    category_labels
)

loan_concerns

                     concern  conversation_count
0    Coverage and conditions                 160
1        Application process                 126
2         Required documents                 120
3    Payment and installment                 108
4               Credit limit                  37
5          Interest and fees                  36
6                Eligibility                  28
7   Renewal and cancellation                  17
8        Approval and status                   8
9          Insurance premium                   6
10           Insurance claim                   3

In [30]:
insurance_concerns = (
    conversation_results.loc[
        conversation_results["insurance_product"],
        concern_columns
    ]
    .sum()
    .sort_values(ascending=False)
    .rename("conversation_count")
    .reset_index()
    .rename(columns={"index": "concern"})
)

insurance_concerns["concern"] = insurance_concerns["concern"].map(
    category_labels
)

insurance_concerns

                     concern  conversation_count
0    Payment and installment                  24
1          Insurance premium                  23
2    Coverage and conditions                  18
3        Application process                   8
4         Required documents                   7
5          Interest and fees                   2
6                Eligibility                   1
7               Credit limit                   1
8        Approval and status                   1
9            Insurance claim                   1
10  Renewal and cancellation                   1

direct answer:

In [31]:
top_loan_concerns = loan_concerns.head(3)["concern"].tolist()
top_insurance_concerns = insurance_concerns.head(3)["concern"].tolist()

print("Top detected loan concerns:")
print(", ".join(top_loan_concerns))

print("\nTop detected insurance concerns:")
print(", ".join(top_insurance_concerns))

Top detected loan concerns:
Coverage and conditions, Application process, Required documents

Top detected insurance concerns:
Payment and installment, Insurance premium, Coverage and conditions

Expected outcome 2: Why customers contacted the chatbot

In [32]:
contact_reason_columns = [
    "eligibility",
    "application_process",
    "required_documents",
    "approval_and_status",
    "interest_and_fees",
    "credit_limit",
    "payment_and_installment",
    "insurance_premium",
    "insurance_claim",
    "coverage_and_conditions",
    "renewal_and_cancellation",
    "campaign_or_promotion",
    "campaign_interest",
    "branch_or_contact"
]

contact_reasons = (
    conversation_results[contact_reason_columns]
    .sum()
    .sort_values(ascending=False)
    .rename("conversation_count")
    .reset_index()
    .rename(columns={"index": "contact_reason"})
)

contact_reasons["contact_reason"] = contact_reasons[
    "contact_reason"
].map(category_labels)

contact_reasons

              contact_reason  conversation_count
0    Coverage and conditions                 166
1          Branch or contact                 159
2    Payment and installment                 145
3        Application process                 139
4         Required documents                 128
5               Credit limit                  37
6          Interest and fees                  37
7      Campaign or promotion                  33
8                Eligibility                  31
9          Insurance premium                  23
10  Renewal and cancellation                  19
11       Approval and status                   9
12           Insurance claim                   4
13         Campaign interest                   2

Direct answer:

In [33]:
top_contact_reasons = contact_reasons.head(5)[
    "contact_reason"
].tolist()

print("The leading detected reasons for contacting the chatbot were:")
print(", ".join(top_contact_reasons))

The leading detected reasons for contacting the chatbot were:
Coverage and conditions, Branch or contact, Payment and installment, Application process, Required documents

Expected outcome 3: Campaign questions and interest

In [34]:
campaign_results = pd.DataFrame({
    "campaign_category": [
        "Campaign or promotion questions",
        "Campaign interest"
    ],
    "conversation_count": [
        conversation_results["campaign_or_promotion"].sum(),
        conversation_results["campaign_interest"].sum()
    ]
})

campaign_results

                 campaign_category  conversation_count
0  Campaign or promotion questions                  33
1                Campaign interest                   2

Compare the two campaign indicators:

In [35]:
campaign_comparison = pd.crosstab(
    conversation_results["campaign_or_promotion"],
    conversation_results["campaign_interest"],
    rownames=["Campaign mentioned"],
    colnames=["Campaign interest detected"]
)

campaign_comparison

Campaign interest detected  False  True
Campaign mentioned
False                         871      2
True                           33      0

Direct answer:

In [36]:
campaign_questions = conversation_results[
    "campaign_or_promotion"
].sum()

campaign_interest = conversation_results[
    "campaign_interest"
].sum()

print(
    "Campaign-related questions were detected in",
    campaign_questions,
    "conversations."
)

print(
    "Campaign-interest language was detected in",
    campaign_interest,
    "conversations."
)

Campaign-related questions were detected in 33 conversations.
Campaign-interest language was detected in 2 conversations.

Expected outcome 4: Conditions, requirements, and needs

In [37]:
need_columns = [
    "eligibility",
    "required_documents",
    "interest_and_fees",
    "credit_limit",
    "payment_and_installment",
    "insurance_premium",
    "coverage_and_conditions"
]

customer_needs = (
    conversation_results[need_columns]
    .sum()
    .sort_values(ascending=False)
    .rename("conversation_count")
    .reset_index()
    .rename(columns={"index": "customer_need"})
)

customer_needs["customer_need"] = customer_needs[
    "customer_need"
].map(category_labels)

customer_needs

             customer_need  conversation_count
0  Coverage and conditions                 166
1  Payment and installment                 145
2       Required documents                 128
3             Credit limit                  37
4        Interest and fees                  37
5              Eligibility                  31
6        Insurance premium                  23

Direct answer:

In [38]:
top_customer_needs = customer_needs.head(5)[
    "customer_need"
].tolist()

print("The most common detected customer needs were:")
print(", ".join(top_customer_needs))

The most common detected customer needs were:
Coverage and conditions, Payment and installment, Required documents, Credit limit, Interest and fees

Expected outcome 5: Marketing insights

In [39]:
conversation_results["has_any_match"] = conversation_results[
    category_columns
].any(axis=1)

matched_conversations = conversation_results[
    "has_any_match"
].sum()

unmatched_conversations = (
    ~conversation_results["has_any_match"]
).sum()

print("Matched conversations:", matched_conversations)
print("Unmatched conversations:", unmatched_conversations)

Matched conversations: 790
Unmatched conversations: 116

Generate preliminary recommendations:

In [40]:
print("Preliminary marketing insights:\n")

print(
    "1. Prioritize campaign information about:",
    ", ".join(top_customer_needs[:3])
)

print(
    "2. Improve chatbot support for:",
    ", ".join(top_contact_reasons[:3])
)

print(
    "3. Review unmatched conversations to identify",
    "new customer needs and missing keywords."
)

print(
    "4. Clearly explain eligibility, conditions,",
    "fees, and application requirements in campaigns."
)

Preliminary marketing insights:

1. Prioritize campaign information about: Coverage and conditions, Payment and installment, Required documents
2. Improve chatbot support for: Coverage and conditions, Branch or contact, Payment and installment
3. Review unmatched conversations to identify new customer needs and missing keywords.
4. Clearly explain eligibility, conditions, fees, and application requirements in campaigns.

## Detailed Drill-Down Analysis

The tables below use the detailed keyword subcategories created in notebook 02. Message-level results mean both topics were detected in the same customer message. Conversation-level results are associations within the same `userID`; they should not be interpreted as same-sentence evidence.

In [41]:
specific_product_columns = [
    "car_loan", "motorcycle_loan", "land_loan", "refinancing",
    "car_insurance", "motorcycle_insurance", "other_insurance_product"
]
specific_concern_columns = [
    "eligibility", "required_documents", "interest_rate", "fees", "credit_limit",
    "loan_installment_repayment", "insurance_premium_payment", "payment_channel",
    "payment_status", "overdue_payment", "insurance_coverage", "insurance_claim",
    "renewal", "cancellation", "approval_application_status"
]
contact_reason_detail_columns = [
    "requesting_information", "applying", "checking_eligibility", "checking_status",
    "making_payment", "making_claim", "renewing", "cancelling",
    "contacting_staff", "finding_branch"
]
condition_requirement_columns = [
    "eligibility", "required_documents", "interest_rate", "fees", "credit_limit",
    "loan_installment_repayment", "insurance_premium_payment", "insurance_coverage"
]
campaign_topic_columns = [
    "campaign_eligibility", "campaign_registration", "campaign_interest",
    "campaign_benefits", "campaign_period_deadline"
]

def available(columns):
    return [column for column in columns if column in keyword_df.columns]

specific_product_columns = available(specific_product_columns)
specific_concern_columns = available(specific_concern_columns)
contact_reason_detail_columns = available(contact_reason_detail_columns)
condition_requirement_columns = available(condition_requirement_columns)
campaign_topic_columns = available(campaign_topic_columns)

In [42]:
def readable_label(column):
    return category_labels.get(column, column.replace("_", " ").title())

def evidence_band(count, max_count):
    if max_count == 0:
        return "No detected evidence"
    share_of_leader = count / max_count
    if share_of_leader >= 0.67:
        return "High among detected combinations"
    if share_of_leader >= 0.34:
        return "Moderate among detected combinations"
    return "Lower among detected combinations"

def combination_summary(df, left_columns, right_columns, level_label, relation_label, top_n=15):
    rows = []
    for left_column in left_columns:
        for right_column in right_columns:
            if left_column == right_column:
                continue
            detected_count = int((df[left_column] & df[right_column]).sum())
            if detected_count > 0:
                rows.append({
                    "left_column": left_column,
                    "right_column": right_column,
                    "combination": f"{readable_label(left_column)} -> {readable_label(right_column)}",
                    "analysis_level": level_label,
                    "relationship": relation_label,
                    "detected_count": detected_count
                })
    if not rows:
        return pd.DataFrame(columns=[
            "rank", "combination", "analysis_level", "relationship",
            "evidence_level", "left_column", "right_column"
        ])
    summary = (
        pd.DataFrame(rows)
        .sort_values("detected_count", ascending=False)
        .head(top_n)
        .reset_index(drop=True)
    )
    max_count = summary["detected_count"].max()
    summary["rank"] = summary.index + 1
    summary["evidence_level"] = summary["detected_count"].apply(
        lambda count: evidence_band(count, max_count)
    )
    return summary[[
        "rank", "combination", "analysis_level", "relationship",
        "evidence_level", "left_column", "right_column"
    ]]

### Outcome 1: Specific Product x Specific Concern

Message-level results are strongest because the product and concern are detected in the same customer message.

In [43]:
message_product_concerns = combination_summary(
    keyword_df, specific_product_columns, specific_concern_columns,
    "Message level", "Direct co-occurrence in the same message"
)
message_product_concerns[["rank", "combination", "analysis_level", "relationship", "evidence_level"]]

,rank,combination,analysis_level,relationship,evidence_level
0,1,Refinancing -> Required documents,Message level,Direct co-occurrence in the same message,High among detected combinations
1,2,Car loan -> Required documents,Message level,Direct co-occurrence in the same message,Moderate among detected combinations
2,3,Refinancing -> Eligibility,Message level,Direct co-occurrence in the same message,Lower among detected combinations
3,4,Refinancing -> Credit limit,Message level,Direct co-occurrence in the same message,Lower among detected combinations
4,5,Motorcycle loan -> Required documents,Message level,Direct co-occurrence in the same message,Lower among detected combinations
5,6,Other insurance product -> Insurance premium p...,Message level,Direct co-occurrence in the same message,Lower among detected combinations
6,7,Other insurance product -> Insurance claim,Message level,Direct co-occurrence in the same message,Lower among detected combinations
7,8,Other insurance product -> Approval or applica...,Message level,Direct co-occurrence in the same message,Lower among detected combinations

In [44]:
conversation_product_concerns = combination_summary(
    conversation_results, specific_product_columns, specific_concern_columns,
    "userID level", "Conversation-level association, not necessarily the same message"
)
conversation_product_concerns[["rank", "combination", "analysis_level", "relationship", "evidence_level"]]

,rank,combination,analysis_level,relationship,evidence_level
0,1,Refinancing -> Required documents,userID level,"Conversation-level association, not necessaril...",High among detected combinations
1,2,Car loan -> Required documents,userID level,"Conversation-level association, not necessaril...",High among detected combinations
2,3,Car insurance -> Insurance premium payment,userID level,"Conversation-level association, not necessaril...",Lower among detected combinations
3,4,Motorcycle loan -> Required documents,userID level,"Conversation-level association, not necessaril...",Lower among detected combinations
4,5,Refinancing -> Credit limit,userID level,"Conversation-level association, not necessaril...",Lower among detected combinations
5,6,Refinancing -> Eligibility,userID level,"Conversation-level association, not necessaril...",Lower among detected combinations
6,7,Car loan -> Credit limit,userID level,"Conversation-level association, not necessaril...",Lower among detected combinations
7,8,Refinancing -> Overdue payment,userID level,"Conversation-level association, not necessaril...",Lower among detected combinations
8,9,Car loan -> Eligibility,userID level,"Conversation-level association, not necessaril...",Lower among detected combinations
9,10,Refinancing -> Insurance premium payment,userID level,"Conversation-level association, not necessaril...",Lower among detected combinations
10,11,Motorcycle loan -> Credit limit,userID level,"Conversation-level association, not necessaril...",Lower among detected combinations
11,12,Refinancing -> Renewal,userID level,"Conversation-level association, not necessaril...",Lower among detected combinations
12,13,Car insurance -> Required documents,userID level,"Conversation-level association, not necessaril...",Lower among detected combinations
13,14,Car loan -> Overdue payment,userID level,"Conversation-level association, not necessaril...",Lower among detected combinations
14,15,Car loan -> Loan installment or repayment,userID level,"Conversation-level association, not necessaril...",Lower among detected combinations

### Outcome 2: Specific Product x Contact Reason

This section explains why customers contacted the chatbot for each identifiable product.

In [45]:
message_product_contact_reasons = combination_summary(
    keyword_df, specific_product_columns, contact_reason_detail_columns,
    "Message level", "Direct co-occurrence in the same message"
)
message_product_contact_reasons[["rank", "combination", "analysis_level", "relationship", "evidence_level"]]

,rank,combination,analysis_level,relationship,evidence_level
0,1,Refinancing -> Requesting information,Message level,Direct co-occurrence in the same message,High among detected combinations
1,2,Refinancing -> Contacting staff,Message level,Direct co-occurrence in the same message,High among detected combinations
2,3,Refinancing -> Checking eligibility,Message level,Direct co-occurrence in the same message,High among detected combinations
3,4,Car insurance -> Requesting information,Message level,Direct co-occurrence in the same message,High among detected combinations
4,5,Car loan -> Finding a branch,Message level,Direct co-occurrence in the same message,Moderate among detected combinations

In [46]:
conversation_product_contact_reasons = combination_summary(
    conversation_results, specific_product_columns, contact_reason_detail_columns,
    "userID level", "Conversation-level association, not necessarily the same message"
)
conversation_product_contact_reasons[["rank", "combination", "analysis_level", "relationship", "evidence_level"]]

,rank,combination,analysis_level,relationship,evidence_level
0,1,Refinancing -> Finding a branch,userID level,"Conversation-level association, not necessaril...",High among detected combinations
1,2,Car loan -> Finding a branch,userID level,"Conversation-level association, not necessaril...",High among detected combinations
2,3,Motorcycle loan -> Finding a branch,userID level,"Conversation-level association, not necessaril...",Moderate among detected combinations
3,4,Refinancing -> Requesting information,userID level,"Conversation-level association, not necessaril...",Moderate among detected combinations
4,5,Car insurance -> Requesting information,userID level,"Conversation-level association, not necessaril...",Moderate among detected combinations
5,6,Motorcycle loan -> Requesting information,userID level,"Conversation-level association, not necessaril...",Moderate among detected combinations
6,7,Car loan -> Requesting information,userID level,"Conversation-level association, not necessaril...",Lower among detected combinations
7,8,Refinancing -> Checking eligibility,userID level,"Conversation-level association, not necessaril...",Lower among detected combinations
8,9,Land loan -> Finding a branch,userID level,"Conversation-level association, not necessaril...",Lower among detected combinations
9,10,Motorcycle loan -> Checking eligibility,userID level,"Conversation-level association, not necessaril...",Lower among detected combinations
10,11,Car loan -> Checking eligibility,userID level,"Conversation-level association, not necessaril...",Lower among detected combinations
11,12,Refinancing -> Contacting staff,userID level,"Conversation-level association, not necessaril...",Lower among detected combinations
12,13,Car loan -> Contacting staff,userID level,"Conversation-level association, not necessaril...",Lower among detected combinations
13,14,Refinancing -> Applying,userID level,"Conversation-level association, not necessaril...",Lower among detected combinations
14,15,Motorcycle loan -> Applying,userID level,"Conversation-level association, not necessaril...",Lower among detected combinations

### Outcome 3: Campaign Topic x Customer Action and Product

Campaign rows are split into customer actions and product associations so campaign interest is easier to interpret.

In [47]:
message_campaign_actions = combination_summary(
    keyword_df, campaign_topic_columns, contact_reason_detail_columns,
    "Message level", "Direct co-occurrence in the same message"
)
message_campaign_actions[["rank", "combination", "analysis_level", "relationship", "evidence_level"]]

Empty DataFrame
Columns: [rank, combination, analysis_level, relationship, evidence_level]
Index: []

In [48]:
conversation_campaign_actions = combination_summary(
    conversation_results, campaign_topic_columns, contact_reason_detail_columns,
    "userID level", "Conversation-level association, not necessarily the same message"
)
conversation_campaign_actions[["rank", "combination", "analysis_level", "relationship", "evidence_level"]]

,rank,combination,analysis_level,relationship,evidence_level
0,1,Campaign benefits -> Finding a branch,userID level,"Conversation-level association, not necessaril...",High among detected combinations
1,2,Campaign interest -> Checking eligibility,userID level,"Conversation-level association, not necessaril...",Moderate among detected combinations
2,3,Campaign interest -> Finding a branch,userID level,"Conversation-level association, not necessaril...",Moderate among detected combinations

In [49]:
message_campaign_products = combination_summary(
    keyword_df, campaign_topic_columns, specific_product_columns,
    "Message level", "Direct co-occurrence in the same message"
)
message_campaign_products[["rank", "combination", "analysis_level", "relationship", "evidence_level"]]

Empty DataFrame
Columns: [rank, combination, analysis_level, relationship, evidence_level]
Index: []

In [50]:
conversation_campaign_products = combination_summary(
    conversation_results, campaign_topic_columns, specific_product_columns,
    "userID level", "Conversation-level association, not necessarily the same message"
)
conversation_campaign_products[["rank", "combination", "analysis_level", "relationship", "evidence_level"]]

,rank,combination,analysis_level,relationship,evidence_level
0,1,Campaign benefits -> Refinancing,userID level,"Conversation-level association, not necessaril...",High among detected combinations
1,2,Campaign benefits -> Car loan,userID level,"Conversation-level association, not necessaril...",Moderate among detected combinations

### Outcome 4: Specific Product x Condition or Requirement

These combinations focus on practical customer needs such as eligibility, documents, interest, fees, limits, repayment, premiums, and coverage.

In [51]:
message_product_conditions = combination_summary(
    keyword_df, specific_product_columns, condition_requirement_columns,
    "Message level", "Direct co-occurrence in the same message"
)
message_product_conditions[["rank", "combination", "analysis_level", "relationship", "evidence_level"]]

,rank,combination,analysis_level,relationship,evidence_level
0,1,Refinancing -> Required documents,Message level,Direct co-occurrence in the same message,High among detected combinations
1,2,Car loan -> Required documents,Message level,Direct co-occurrence in the same message,Moderate among detected combinations
2,3,Refinancing -> Eligibility,Message level,Direct co-occurrence in the same message,Lower among detected combinations
3,4,Refinancing -> Credit limit,Message level,Direct co-occurrence in the same message,Lower among detected combinations
4,5,Motorcycle loan -> Required documents,Message level,Direct co-occurrence in the same message,Lower among detected combinations
5,6,Other insurance product -> Insurance premium p...,Message level,Direct co-occurrence in the same message,Lower among detected combinations

In [52]:
conversation_product_conditions = combination_summary(
    conversation_results, specific_product_columns, condition_requirement_columns,
    "userID level", "Conversation-level association, not necessarily the same message"
)
conversation_product_conditions[["rank", "combination", "analysis_level", "relationship", "evidence_level"]]

,rank,combination,analysis_level,relationship,evidence_level
0,1,Refinancing -> Required documents,userID level,"Conversation-level association, not necessaril...",High among detected combinations
1,2,Car loan -> Required documents,userID level,"Conversation-level association, not necessaril...",High among detected combinations
2,3,Car insurance -> Insurance premium payment,userID level,"Conversation-level association, not necessaril...",Lower among detected combinations
3,4,Motorcycle loan -> Required documents,userID level,"Conversation-level association, not necessaril...",Lower among detected combinations
4,5,Refinancing -> Credit limit,userID level,"Conversation-level association, not necessaril...",Lower among detected combinations
5,6,Refinancing -> Eligibility,userID level,"Conversation-level association, not necessaril...",Lower among detected combinations
6,7,Car loan -> Credit limit,userID level,"Conversation-level association, not necessaril...",Lower among detected combinations
7,8,Refinancing -> Insurance premium payment,userID level,"Conversation-level association, not necessaril...",Lower among detected combinations
8,9,Car loan -> Eligibility,userID level,"Conversation-level association, not necessaril...",Lower among detected combinations
9,10,Motorcycle loan -> Credit limit,userID level,"Conversation-level association, not necessaril...",Lower among detected combinations
10,11,Car insurance -> Required documents,userID level,"Conversation-level association, not necessaril...",Lower among detected combinations
11,12,Refinancing -> Loan installment or repayment,userID level,"Conversation-level association, not necessaril...",Lower among detected combinations
12,13,Motorcycle loan -> Insurance premium payment,userID level,"Conversation-level association, not necessaril...",Lower among detected combinations
13,14,Car loan -> Loan installment or repayment,userID level,"Conversation-level association, not necessaril...",Lower among detected combinations
14,15,Car loan -> Insurance premium payment,userID level,"Conversation-level association, not necessaril...",Lower among detected combinations

### Validation of Leading Combinations

This validation checks that the leading combinations come from rows where both detailed flags are present. Customer-message text is not displayed.

In [53]:
def validation_table(summary_table, source_df, validation_name, top_n=5):
    rows = []
    for _, row in summary_table.head(top_n).iterrows():
        both_flags_detected = bool(
            (source_df[row["left_column"]] & source_df[row["right_column"]]).any()
        )
        rows.append({
            "validation_section": validation_name,
            "combination": row["combination"],
            "analysis_level": row["analysis_level"],
            "check": "Both flags appear in the source level used for this table",
            "status": "Pass" if both_flags_detected else "Review needed"
        })
    return pd.DataFrame(rows)

validation_sections = [
    validation_table(message_product_concerns, keyword_df, "Message-level product concerns"),
    validation_table(conversation_product_concerns, conversation_results, "Conversation-level product concern associations"),
    validation_table(message_product_contact_reasons, keyword_df, "Message-level contact reasons"),
    validation_table(message_campaign_products, keyword_df, "Message-level campaign products"),
    validation_table(message_product_conditions, keyword_df, "Message-level product conditions")
]
leading_combination_validation = pd.concat(
    [table for table in validation_sections if not table.empty],
    ignore_index=True
)
leading_combination_validation

,validation_section,combination,analysis_level,check,status
0,Message-level product concerns,Refinancing -> Required documents,Message level,Both flags appear in the source level used for...,Pass
1,Message-level product concerns,Car loan -> Required documents,Message level,Both flags appear in the source level used for...,Pass
2,Message-level product concerns,Refinancing -> Eligibility,Message level,Both flags appear in the source level used for...,Pass
3,Message-level product concerns,Refinancing -> Credit limit,Message level,Both flags appear in the source level used for...,Pass
4,Message-level product concerns,Motorcycle loan -> Required documents,Message level,Both flags appear in the source level used for...,Pass
5,Conversation-level product concern associations,Refinancing -> Required documents,userID level,Both flags appear in the source level used for...,Pass
6,Conversation-level product concern associations,Car loan -> Required documents,userID level,Both flags appear in the source level used for...,Pass
7,Conversation-level product concern associations,Car insurance -> Insurance premium payment,userID level,Both flags appear in the source level used for...,Pass
8,Conversation-level product concern associations,Motorcycle loan -> Required documents,userID level,Both flags appear in the source level used for...,Pass
9,Conversation-level product concern associations,Refinancing -> Credit limit,userID level,Both flags appear in the source level used for...,Pass
10,Message-level contact reasons,Refinancing -> Requesting information,Message level,Both flags appear in the source level used for...,Pass
11,Message-level contact reasons,Refinancing -> Contacting staff,Message level,Both flags appear in the source level used for...,Pass
12,Message-level contact reasons,Refinancing -> Checking eligibility,Message level,Both flags appear in the source level used for...,Pass
13,Message-level contact reasons,Car insurance -> Requesting information,Message level,Both flags appear in the source level used for...,Pass
14,Message-level contact reasons,Car loan -> Finding a branch,Message level,Both flags appear in the source level used for...,Pass
15,Message-level product conditions,Refinancing -> Required documents,Message level,Both flags appear in the source level used for...,Pass
16,Message-level product conditions,Car loan -> Required documents,Message level,Both flags appear in the source level used for...,Pass
17,Message-level product conditions,Refinancing -> Eligibility,Message level,Both flags appear in the source level used for...,Pass
18,Message-level product conditions,Refinancing -> Credit limit,Message level,Both flags appear in the source level used for...,Pass
19,Message-level product conditions,Motorcycle loan -> Required documents,Message level,Both flags appear in the source level used for...,Pass

### Outcome 5: Concise Marketing Interpretation

The statements below are generated from the calculated leading combinations. They avoid customer-message text and label `userID`-level results as associations.

In [54]:
def top_combinations(summary_table, top_n=3):
    if summary_table.empty:
        return []
    return summary_table.head(top_n)["combination"].tolist()

def format_items(items):
    if not items:
        return "No specific combinations were detected with the current keyword rules."
    return "; ".join(items)

interpretations = [
    {
        "expected_outcome": "1. Customer concerns about loan and insurance products",
        "message_level_interpretation": format_items(top_combinations(message_product_concerns)),
        "conversation_level_association": format_items(top_combinations(conversation_product_concerns)),
        "limitation": "Keyword matching shows topic co-occurrence, not customer sentiment or intent strength."
    },
    {
        "expected_outcome": "2. Why customers contacted the chatbot",
        "message_level_interpretation": format_items(top_combinations(message_product_contact_reasons)),
        "conversation_level_association": format_items(top_combinations(conversation_product_contact_reasons)),
        "limitation": "A contact reason may be missed if the customer used wording outside the keyword dictionary."
    },
    {
        "expected_outcome": "3. Questions and interest related to marketing campaigns",
        "message_level_interpretation": format_items(top_combinations(message_campaign_actions)),
        "conversation_level_association": format_items(top_combinations(conversation_campaign_actions)),
        "limitation": "Campaign associations should be reviewed carefully because campaign wording can overlap with general promotion language."
    },
    {
        "expected_outcome": "4. Product conditions, requirements, and customer needs",
        "message_level_interpretation": format_items(top_combinations(message_product_conditions)),
        "conversation_level_association": format_items(top_combinations(conversation_product_conditions)),
        "limitation": "The table identifies recurring requirement topics but does not verify whether the customer received a correct answer."
    },
    {
        "expected_outcome": "5. Marketing insights",
        "message_level_interpretation": (
            "Prioritize campaign and chatbot content around the leading product-specific concerns, "
            "contact reasons, and condition or requirement combinations shown above."
        ),
        "conversation_level_association": format_items(top_combinations(conversation_campaign_products)),
        "limitation": "Use conversation-level campaign-product rows as associations only; they may come from separate messages by the same userID."
    }
]
final_interpretation = pd.DataFrame(interpretations)
final_interpretation

,expected_outcome,message_level_interpretation,conversation_level_association,limitation
0,1. Customer concerns about loan and insurance ...,Refinancing -> Required documents; Car loan ->...,Refinancing -> Required documents; Car loan ->...,"Keyword matching shows topic co-occurrence, no..."
1,2. Why customers contacted the chatbot,Refinancing -> Requesting information; Refinan...,Refinancing -> Finding a branch; Car loan -> F...,A contact reason may be missed if the customer...
2,3. Questions and interest related to marketing...,No specific combinations were detected with th...,Campaign benefits -> Finding a branch; Campaig...,Campaign associations should be reviewed caref...
3,"4. Product conditions, requirements, and custo...",Refinancing -> Required documents; Car loan ->...,Refinancing -> Required documents; Car loan ->...,The table identifies recurring requirement top...
4,5. Marketing insights,Prioritize campaign and chatbot content around...,Campaign benefits -> Refinancing; Campaign ben...,Use conversation-level campaign-product rows a...